[package]
name = "interferon"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
histo = "1.0.0"
indicatif = "0.17.8"
rand = "0.8.5"
rayon = "1.10.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"

[build]
rustflags = "-C target-cpu=native"
